In [1]:
import numpy as np
import copy
from PIL import Image
from numpy import linalg as LA

In [11]:
    def convert_to_flat(Array):
        #flat_arr = np.ndarray.flatten(Array).astype(int)
        flat_arr=Array
        with np.nditer(flat_arr, op_flags=['readwrite']) as it:
          for x in it:
            #print(x, end = '')
            if x<0.5:
              x[...] = -1
            else:
              x[...] =  1
        return flat_arr

In [12]:
class hopfield:
    def __init__(self,x1):
        (self.size1,)=x1.shape
        print(self.size1)
        self.L=np.zeros((self.size1,self.size1))
        self.W1=np.outer(x1,x1)
        self.W3=self.W1
        self.Wp=self.W1
        self.Test=self.Wp
        print("Input vector")
        print(x1)
        print("W_p matrix")
        print(self.Wp)
        print("Shape Wp:")
        print(self.Wp.shape)
        print("Norm %f " % LA.norm(self.Wp))
        
    def size(self):
        print(self.size1)
    def update(self,x2):
        W2=np.outer(x2,x2)
        (a,)=x2.shape
        if a != self.size1:
            print("Wrong input vector")
        W3=self.Wp+W2
        print("W3:")
        print(W3)
        self.L=W3.diagonal()*np.identity(self.size1)
        print("WL:")
        print(self.L)
        self.Wp=W3-self.L
        print("Wp:")
        print(self.Wp)
        print("Norm %f " % LA.norm(self.Wp))
    def forget(self,input):
        x2=input #self.convert_to_flat_inverted(input)
        (a,)=input.shape
        print(a)
        print("x2:")
        print(x2)
        W2=np.outer(x2,x2)
        if a != self.size1:
            print("Wrong input vector")
        W3=self.Wp+self.L
        #print("W3:")
        #print(W3)
        #self.L=W3.diagonal()*np.identity(self.size1)
        #print("WL:")
        #print(L)
        self.Wp=W3-W2
        print("Wp:")
        print(self.Wp)
        print("Norm %f " % LA.norm(self.Wp))
    def convert_to_flat_inverted(self,input):
        (a,)=input.shape
        if a != self.size1:
            print("Wrong input at convert to flat_inverted")
        with np.nditer(input, op_flags=['readwrite']) as it:
            for x in it:
         #       print(x, end = '')
                if x>=1:
                    x[...] = -1
         #          print("L= %i " % x)
                else:
                    x[...] = 1
          #         print("L= %i " % x)
        
        return input
    def query(self,input):
        (a,)=input.shape
        if a != self.size1:
            print("Wrong input query")
        Test=self.Wp.dot(input)
        old=copy.deepcopy(Test)
        dist=100000
        while(dist>0.1):
            with np.nditer(Test, op_flags=['readwrite']) as it:
                for x in it:
                    if x>0:
                        x[...] = 1
                    else:
                        x[...] = -1
                print(old)
                print(Test)
                dist = np.linalg.norm(old-Test)
                print("Distancia: %f " %dist)
                old=copy.deepcopy(Test)
                Test=self.Wp.dot(Test) 
        print(old)
        print("Norm %f " % LA.norm(self.Wp))
    
    def matrices(self): #Displays the NxN matrix
        W3=self.Wp
        print("NxN Matrix Wp:")
        print(W3) 
        w, v = LA.eig(W3)
        print("w:")
        print(w)
        print("v:")
        print(v)


In [13]:
def loader(path):
  plane=np.load(path)
  print(plane)
  plane=plane.reshape(64,)
  plane=convert_to_flat(plane)
  print(plane)
  print(plane.shape)
  return plane



In [14]:
plane1=loader("/content/drive/MyDrive/plane1_gabor.npy")
plane2=loader("/content/drive/MyDrive/plane2_gabor.npy")
plane2_half=loader("/content/drive/MyDrive/plane2_half_gabor.npy")
plane2_half2=loader("/content/drive/MyDrive/plane2_half2_gabor.npy")
plane3=loader("/content/drive/MyDrive/plane3_gabor.npy")

[[0.         0.         0.23854132 0.         0.         0.83114195
  0.         0.         0.         0.         0.         0.
  0.         0.65543914 0.         0.         0.         0.
  0.         0.26491842 0.         0.         0.04153139 0.
  0.         0.         0.         0.         0.5161178  0.5045015
  0.         0.         0.06258626 0.         0.27689674 0.
  0.17107666 0.46948224 0.         0.         0.         0.
  0.         0.         0.         1.         0.2844023  0.
  0.4875122  0.         0.         0.23480894 0.02611175 0.
  0.         0.         0.         0.19777642 0.         0.
  0.25521275 0.         0.         0.35510457]]
[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
(64,)
[[0.         0.         0.6951421  0.         0.         0.6329402
  0

In [15]:
hippocampus=hopfield(plane1)

64
Input vector
[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
W_p matrix
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Shape Wp:
(64, 64)
Norm 64.000000 


In [16]:
hippocampus.matrices()

NxN Matrix Wp:
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
w:
[ 0.0000000e+00  6.4000000e+01  0.0000000e+00  1.3342198e-30
  0.0000000e+00 -0.0000000e+00 -0.0000000e+00 -0.0000000e+00
 -0.0000000e+00 -0.0000000e+00  0.0000000e+00  0.0000000e+00
 -0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0

In [17]:
hippocampus.update(plane1)
hippocampus.update(plane1)
hippocampus.update(plane1)


W3:
[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
WL:
[[2. 0. 0. ... 0. 0. 0.]
 [0. 2. 0. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 2. 0. 0.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 0. ... 0. 0. 2.]]
Wp:
[[0. 2. 2. ... 2. 2. 2.]
 [2. 0. 2. ... 2. 2. 2.]
 [2. 2. 0. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 0. 2. 2.]
 [2. 2. 2. ... 2. 0. 2.]
 [2. 2. 2. ... 2. 2. 0.]]
Norm 126.996063 
W3:
[[1. 3. 3. ... 3. 3. 3.]
 [3. 1. 3. ... 3. 3. 3.]
 [3. 3. 1. ... 3. 3. 3.]
 ...
 [3. 3. 3. ... 1. 3. 3.]
 [3. 3. 3. ... 3. 1. 3.]
 [3. 3. 3. ... 3. 3. 1.]]
WL:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
Wp:
[[0. 3. 3. ... 3. 3. 3.]
 [3. 0. 3. ... 3. 3. 3.]
 [3. 3. 0. ... 3. 3. 3.]
 ...
 [3. 3. 3. ... 0. 3. 3.]
 [3. 3. 3. ... 3. 0. 3.]
 [3. 3. 3. ... 3. 3. 0.]]
Norm 190.494094 
W3:
[[

In [18]:
hippocampus.query(plane1)



[-252. -252. -252. -252. -252.  252. -252. -252. -252. -252. -252. -252.
 -252.  252. -252. -252. -252. -252. -252. -252. -252. -252. -252. -252.
 -252. -252. -252. -252.  252.  252. -252. -252. -252. -252. -252. -252.
 -252. -252. -252. -252. -252. -252. -252. -252. -252.  252. -252. -252.
 -252. -252. -252. -252. -252. -252. -252. -252. -252. -252. -252. -252.
 -252. -252. -252. -252.]
[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
Distancia: 2008.000000 
[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1

In [19]:
hippocampus.query(plane2)

[-196. -196. -204. -196. -196.  196. -196. -196. -204. -196. -196. -204.
 -196.  196. -196. -196. -196. -196. -196. -196. -196. -196. -196. -196.
 -196. -196. -196. -196.  196.  204. -196. -196. -204. -196. -196. -196.
 -196. -196. -196. -196. -196. -196. -196. -196. -204.  196. -196. -196.
 -196. -196. -196. -196. -196. -196. -196. -196. -196. -196. -196. -196.
 -196. -196. -196. -204.]
[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
Distancia: 1567.127308 
[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1

In [20]:
bart1=loader("/content/drive/MyDrive/faces/bart/bart_color1_gabor.npy")
bart2=loader("/content/drive/MyDrive/faces/bart/bart_color2_gabor.npy")

[[0.87540334 0.84545904 0.9020257  0.         0.         0.4378683
  0.52484024 0.         0.30518302 0.         0.04945176 0.9663766
  0.         0.12575488 0.         0.         0.3972863  0.90301573
  0.17305872 0.41558707 0.         0.         0.15336245 0.14800648
  0.34824544 0.7937718  0.         1.         0.7136906  0.51908445
  0.         0.         0.3253594  0.6220409  0.         0.7725575
  0.25859424 0.21914873 0.02019773 0.2750908  0.97271526 0.2593102
  0.         0.         0.62662995 0.59721375 0.18775752 0.
  0.9705644  0.         0.         0.08173019 0.03279145 0.13120425
  0.         0.39123735 0.         0.38351357 0.         0.
  0.21438442 0.         0.         0.92099947]]
[ 1.  1.  1. -1. -1. -1.  1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1.  1.
 -1. -1. -1. -1. -1. -1. -1.  1. -1.  1.  1.  1. -1. -1. -1.  1. -1.  1.
 -1. -1. -1. -1.  1. -1. -1. -1.  1.  1. -1. -1.  1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.]
(64,)
[[2.27725804e-01 2.258714

In [21]:
hippocampus.update(bart1)
hippocampus.update(bart1)
hippocampus.update(bart1)


W3:
[[1. 5. 5. ... 3. 3. 5.]
 [5. 1. 5. ... 3. 3. 5.]
 [5. 5. 1. ... 3. 3. 5.]
 ...
 [3. 3. 3. ... 1. 5. 3.]
 [3. 3. 3. ... 5. 1. 3.]
 [5. 5. 5. ... 3. 3. 1.]]
WL:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
Wp:
[[0. 5. 5. ... 3. 3. 5.]
 [5. 0. 5. ... 3. 3. 5.]
 [5. 5. 0. ... 3. 3. 5.]
 ...
 [3. 3. 3. ... 0. 5. 3.]
 [3. 3. 3. ... 5. 0. 3.]
 [5. 5. 5. ... 3. 3. 0.]]
Norm 276.086943 
W3:
[[1. 6. 6. ... 2. 2. 6.]
 [6. 1. 6. ... 2. 2. 6.]
 [6. 6. 1. ... 2. 2. 6.]
 ...
 [2. 2. 2. ... 1. 6. 2.]
 [2. 2. 2. ... 6. 1. 2.]
 [6. 6. 6. ... 2. 2. 1.]]
WL:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
Wp:
[[0. 6. 6. ... 2. 2. 6.]
 [6. 0. 6. ... 2. 2. 6.]
 [6. 6. 0. ... 2. 2. 6.]
 ...
 [2. 2. 2. ... 0. 6. 2.]
 [2. 2. 2. ... 6. 0. 2.]
 [6. 6. 6. ... 2. 2. 0.]]
Norm 309.838668 
W3:
[[

In [22]:
hippocampus.update(bart2)
hippocampus.update(bart2)

W3:
[[1. 8. 6. ... 2. 2. 6.]
 [8. 1. 6. ... 2. 2. 6.]
 [6. 6. 1. ... 0. 0. 8.]
 ...
 [2. 2. 0. ... 1. 8. 0.]
 [2. 2. 0. ... 8. 1. 0.]
 [6. 6. 8. ... 0. 0. 1.]]
WL:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
Wp:
[[0. 8. 6. ... 2. 2. 6.]
 [8. 0. 6. ... 2. 2. 6.]
 [6. 6. 0. ... 0. 0. 8.]
 ...
 [2. 2. 0. ... 0. 8. 0.]
 [2. 2. 0. ... 8. 0. 0.]
 [6. 6. 8. ... 0. 0. 0.]]
Norm 384.124980 
W3:
[[ 1.  9.  5. ...  3.  3.  5.]
 [ 9.  1.  5. ...  3.  3.  5.]
 [ 5.  5.  1. ... -1. -1.  9.]
 ...
 [ 3.  3. -1. ...  1.  9. -1.]
 [ 3.  3. -1. ...  9.  1. -1.]
 [ 5.  5.  9. ... -1. -1.  1.]]
WL:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
Wp:
[[ 0.  9.  5. ...  3.  3.  5.]
 [ 9.  0.  5. ...  3.  3.  5.]
 [ 5.  5.  0. ... -1. -1.  9.]
 ...
 [ 3.  3. -1. ...  0.  9. -1.]
 [ 3.  3. -1. 

In [23]:
hippocampus.query(bart1)

[ -17.  -17.  127. -383. -383.   17.  -17. -383. -383. -383. -383.  127.
 -383.   17. -383. -383. -383.  -17. -383. -239. -383. -383. -383. -383.
 -383.  -17. -383.  127.  383.  239. -383. -383. -383.  -17. -383.  127.
 -383. -383. -383. -239.  -17. -383. -383. -383.  127.  383. -383. -383.
  127. -383. -383. -239. -383. -383. -383. -383. -383. -383. -383. -383.
 -239. -383. -383.  127.]
[-1. -1.  1. -1. -1.  1. -1. -1. -1. -1. -1.  1. -1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1. -1. -1. -1. -1. -1.  1.
 -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.]
Distancia: 2582.903018 
[-1. -1.  1. -1. -1.  1. -1. -1. -1. -1. -1.  1. -1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1. -1. -1. -1. -1. -1.  1.
 -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.]
[-1. -1.  1. -1. -1.  1. -1. -1. -1. -1. -1.  1. -1.  1. -1. -1

In [24]:
hippocampus.query(plane1)

[-231. -231.  -71. -423. -423.  231. -231. -423. -423. -423. -423.  -71.
 -423.  231. -423. -423. -423. -231. -423. -263. -423. -423. -423. -423.
 -423. -231. -423.  -71.  423.  263. -423. -423. -423. -231. -423.  -71.
 -423. -423. -423. -263. -231. -423. -423. -423.  -71.  423. -423. -423.
  -71. -423. -423. -263. -423. -423. -423. -423. -423. -423. -423. -423.
 -263. -423. -423.  -71.]
[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
Distancia: 2917.401584 
[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1

In [ ]:
hippocampus.query(plane2)

[  19. -223. -223.  -19. -223. -223.  -33.  237.   33. -223. -223.   19.
   33.   33. -223. -223.   19.   19. -223.   33.  223. -223.  -19.  223.
   33.  237.  -19. -223. -223. -223.   33.  -19. -223. -223. -223. -223.
 -223.  -19.   33. -237.   33. -223. -223. -223. -223. -223. -223. -223.
 -223.   19.   33. -223.  -33.  -19. -223.  223. -223.  223. -223. -223.
 -223.   33. -223.  237.]
[ 1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1.  1.  1. -1. -1.  1.  1.
 -1.  1.  1. -1. -1.  1.  1.  1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1.
 -1. -1.  1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1.
 -1.  1. -1.  1. -1. -1. -1.  1. -1.  1.]
Distancia: 1436.016713 
[ 1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1.  1.  1. -1. -1.  1.  1.
 -1.  1.  1. -1. -1.  1.  1.  1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1.
 -1. -1.  1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1.
 -1.  1. -1.  1. -1. -1. -1.  1. -1.  1.]
[ 1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1.  1.  1. -1. -1

In [ ]:
hippocampus.query(plane2_half)

[  29. -197. -197.  -29. -197. -197.  -43.  197.   43. -197. -197.   29.
   43.   29. -197. -197.   29.   29. -197.   43.  197. -197.  -29.  211.
   43.  211.  -29. -197. -197. -197.   43.  -29. -197. -197. -197. -197.
 -211.  -29.   43. -211.   43. -197. -197. -197. -197. -197. -197. -197.
 -197.   29.   43. -197.  -43.  -29. -197.  197. -197.  197. -197. -211.
 -197.   43. -197.  211.]
[ 1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1.  1.  1. -1. -1.  1.  1.
 -1.  1.  1. -1. -1.  1.  1.  1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1.
 -1. -1.  1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1.
 -1.  1. -1.  1. -1. -1. -1.  1. -1.  1.]
Distancia: 1279.832802 
[ 1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1.  1.  1. -1. -1.  1.  1.
 -1.  1.  1. -1. -1.  1.  1.  1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1.
 -1. -1.  1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1.
 -1.  1. -1.  1. -1. -1. -1.  1. -1.  1.]
[ 1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1.  1.  1. -1. -1

In [ ]:
hippocampus.query(plane2_half2)

[  33. -225. -225.  -33. -225. -225.  -47.  225.   47. -225. -225.   33.
   47.   33. -225. -225.   33.   33. -225.   47.  225. -225.  -33.  239.
   47.  239.  -33. -225. -225. -225.   47.  -33. -225. -225. -225. -225.
 -225.  -33.   47. -239.   47. -225. -225. -225. -225. -225. -225. -225.
 -225.   33.   47. -225.  -47.  -33. -225.  225. -225.  225. -225. -239.
 -225.   47. -225.  225.]
[ 1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1.  1.  1. -1. -1.  1.  1.
 -1.  1.  1. -1. -1.  1.  1.  1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1.
 -1. -1.  1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1.
 -1.  1. -1.  1. -1. -1. -1.  1. -1.  1.]
Distancia: 1455.558999 
[ 1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1.  1.  1. -1. -1.  1.  1.
 -1.  1.  1. -1. -1.  1.  1.  1. -1. -1. -1. -1.  1. -1. -1. -1. -1. -1.
 -1. -1.  1. -1.  1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1.
 -1.  1. -1.  1. -1. -1. -1.  1. -1.  1.]
[ 1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1.  1.  1.  1. -1. -1