In [1]:
import numpy as np
import copy
from PIL import Image
from numpy import linalg as LA


In [2]:
class hopfield:
    def __init__(self,x1):
        (self.size1,)=x1.shape
        print(self.size1)
        self.L=np.zeros((self.size1,self.size1))
        self.W1=np.outer(x1,x1)
        self.W3=self.W1
        self.Wp=self.W1
        self.Test=self.Wp
        print(self.Wp)
        print("Norm %f " % LA.norm(self.Wp))
        
    def size(self):
        print(self.size1)
    def update(self,x2):
        W2=np.outer(x2,x2)
        (a,)=x2.shape
        if a != self.size1:
            print("Wrong input vector")
        W3=self.Wp+W2
        print("W3:")
        print(W3)
        self.L=W3.diagonal()*np.identity(self.size1)
        print("WL:")
        print(self.L)
        self.Wp=W3-self.L
        print("Wp:")
        print(self.Wp)
        print("Norm %f " % LA.norm(self.Wp))
    def forget(self,input):
        x2=input #self.convert_to_flat_inverted(input)
        (a,)=input.shape
        print(a)
        print("x2:")
        print(x2)
        W2=np.outer(x2,x2)
        if a != self.size1:
            print("Wrong input vector")
        W3=self.Wp+self.L
        #print("W3:")
        #print(W3)
        #self.L=W3.diagonal()*np.identity(self.size1)
        #print("WL:")
        #print(L)
        self.Wp=W3-W2
        print("Wp:")
        print(self.Wp)
        print("Norm %f " % LA.norm(self.Wp))
    def convert_to_flat_inverted(self,input):
        (a,)=input.shape
        if a != self.size1:
            print("Wrong input at convert to flat_inverted")
        with np.nditer(input, op_flags=['readwrite']) as it:
            for x in it:
         #       print(x, end = '')
                if x>=1:
                    x[...] = -1
         #          print("L= %i " % x)
                else:
                    x[...] = 1
          #         print("L= %i " % x)
        
        return input
    def query(self,input):
        (a,)=input.shape
        if a != self.size1:
            print("Wrong input query")
        Test=self.Wp.dot(input)
        old=copy.deepcopy(Test)
        dist=100000
        while(dist>0.1):
            with np.nditer(Test, op_flags=['readwrite']) as it:
                for x in it:
                    if x>0:
                        x[...] = 1
                    else:
                        x[...] = -1
                print(old)
                print(Test)
                dist = np.linalg.norm(old-Test)
                print("Distancia: %f " %dist)
                old=copy.deepcopy(Test)
                Test=self.Wp.dot(Test)
        print(old)
    
    def W_p (self):
        W3=self.Wp
        print("Wp:")
        print(W3) 
        w, v = LA.eig(W3)
        print("w:")
        print(w)
        print("v:")
        print(v)

In [3]:
class HP:
    def __init__ (self,image):
        x1=self.convert_to_flat(image)
        (self.size1,)=x1.shape
        print("Size")
        print(self.size1)
        self.L=np.zeros((self.size1,self.size1))
        self.W1=np.outer(x1,x1)
        self.W3=self.W1
        self.Wp=self.W1
        #print("Wp")
        #print(self.Wp)
        print("Norm %f " % LA.norm(self.Wp))

    def convert_to_flat(self,image):
        #it converst to 1 or -1 images
        img = Image.open(image).convert('L')
        #img = img.convert('1')
        newsize = (100, 100)
        img = img.resize(newsize)  
        arr = np.array(img)
        self.shape = arr.shape
        flat_arr = np.ndarray.flatten(arr).astype(int)
        vector = np.matrix(flat_arr)
        with np.nditer(flat_arr, op_flags=['readwrite']) as it:
            for x in it:
                #print(x, end = '')
                if x<127:
                    x[...] = -1
                #    print("bin - = %i " % x)
                else:
                    x[...] =  1
                #    print("bin= + =%i " % x)
        
        vector2 = copy.deepcopy(flat_arr)
        vector2.astype(np.int8)
        #print("Binario")
        with np.nditer(vector2, op_flags=['readwrite']) as it:
            for x in it:
         #       print(x, end = '')
                if x>=1:
                    x[...] = 255
          #          print("L= %i " % x)
                else:
                    x[...] = 0
           #         print("L= %i " % x)
        arr2 = np.asarray(vector2).reshape(self.shape).astype(np.int8)
        # make a PIL image
        img2 = Image.fromarray(arr2, 'L')
        img2.show()
        return flat_arr
    def convert_to_flat_inverted(self,image):
        #it converst to 1 or -1 images
        img = Image.open(image).convert('L')
        #img = img.convert('1')
        newsize = (100, 100)
        img = img.resize(newsize)  
        arr = np.array(img)
        self.shape = arr.shape
        flat_arr = np.ndarray.flatten(arr).astype(int)
        vector = np.matrix(flat_arr)
        with np.nditer(flat_arr, op_flags=['readwrite']) as it:
            for x in it:
                #print(x, end = '')
                if x<127:
                    x[...] = 1
                #    print("bin - = %i " % x)
                else:
                    x[...] =  -1
                #    print("bin= + =%i " % x)
        
        vector2 = copy.deepcopy(flat_arr)
        vector2.astype(np.int8)
        #print("Binario")
        with np.nditer(vector2, op_flags=['readwrite']) as it:
            for x in it:
         #       print(x, end = '')
                if x>=1:
                    x[...] = 255
          #          print("L= %i " % x)
                else:
                    x[...] = 0
           #         print("L= %i " % x)
        arr2 = np.asarray(vector2).reshape(self.shape).astype(np.int8)
        # make a PIL image
        img2 = Image.fromarray(arr2, 'L')
        img2.show()
        return flat_arr

    def size(self):
        print(self.size1)
    def update(self,image):
        x2=self.convert_to_flat(image)
        (a,)=x2.shape
        print(a)
        W2=np.outer(x2,x2)
        if a != self.size1:
            print("Wrong input vector")
        W3=self.Wp+W2
        #print("W3:")
        #print(W3)
        self.L=W3.diagonal()*np.identity(self.size1)
        #print("WL:")
        #print(L)
        self.Wp=W3-self.L
        #print("Wp:")
        #print(self.Wp)
        print("Norm %f " % LA.norm(self.Wp))
    def forget(self,image):
        x2=self.convert_to_flat(image)
        (a,)=input.shape
        print(a)
        print("x2:")
        print(x2)
        W2=np.outer(x2,x2)
        if a != self.size1:
            print("Wrong input vector: " )
        W3=self.Wp+self.L
        #print("W3:")
        #print(W3)
        #self.L=W3.diagonal()*np.identity(self.size1)
        #print("WL:")
        #print(L)
        self.Wp=W3-W2
        print("Wp:")
        print(self.Wp)
        print("Norm %f " % LA.norm(self.Wp))
    def query(self,image):
        input=self.convert_to_flat(image)
        (a,)=input.shape
        print("Size:")
        print(a)
        if a != self.size1:
            print("Wrong input query")
        self.Test=self.Wp.dot(input)
        dist=1000000
        old=input
        while(dist>0.1):
            with np.nditer(self.Test, op_flags=['readwrite']) as it:
                for x in it:
                    if x>0:
                        x[...] = 1
                    else:
                        x[...] = -1
            print(self.Test)
            dist = np.linalg.norm(old-self.Test)
            print("Distancia: %f " %dist)
            old=copy.deepcopy(self.Test)
            self.Test=self.Wp.dot(self.Test)
        self.Test=copy.deepcopy(old)    
            
        with np.nditer(self.Test, op_flags=['readwrite']) as it:
            for x in it:
                if x>0:
                    x[...] = 255
                else:
                    x[...] = 0
        arr2 = np.asarray(self.Test).reshape(self.shape).astype(np.int8)
        # make a PIL image
        img2 = Image.fromarray(arr2, 'L')
        img2.show()
    def W_p (self):
        W3=self.Wp
        print("Wp:")
        print(W3) 
        w, v = LA.eig(W3)
        print("w:")
        print(w)
        
        

In [83]:
a=HP("Homer.png")

Size
10000
Norm 10000.000000 


In [5]:
a.W_p()

Wp:
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
w:
[ 1.00000000e+004+0.00000000e+00j  3.43445280e-012+0.00000000e+00j
 -4.42572934e-013+2.49190397e-12j ... -3.77522466e-275+0.00000000e+00j
  9.31839699e-277+0.00000000e+00j -4.79288491e-278+0.00000000e+00j]


In [86]:
a.update("Bart.png")



10000
Norm 34577.473361 


In [ ]:
a.forget("Bart.png")

In [7]:
a.W_p()

Wp:
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
w:
[ 1.00000000e+004+0.00000000e+00j  3.43445280e-012+0.00000000e+00j
 -4.42572934e-013+2.49190397e-12j ... -3.77522466e-275+0.00000000e+00j
  9.31839699e-277+0.00000000e+00j -4.79288491e-278+0.00000000e+00j]


In [6]:
a.forget("Homer.png")

AttributeError: 'function' object has no attribute 'shape'

In [ ]:
a.update("lisa.png")
a.update("lisa.png")
a.update("lisa.png")
a.update("lisa.png")


In [76]:
a.update("lisa.png")

10000
Norm 23904.210173 


In [87]:
a.query("Bart2.png")

Size:
10000
[-1. -1. -1. ... -1. -1. -1.]
Distancia: 39.293765 
[-1. -1. -1. ... -1. -1. -1.]
Distancia: 0.000000 


In [80]:
a.query("lisa.png")

Size:
10000
[1. 1. 1. ... 1. 1. 1.]
Distancia: 57.236352 
[1. 1. 1. ... 1. 1. 1.]
Distancia: 0.000000 


In [81]:
a.query("Bart2.png")

Size:
10000
[1. 1. 1. ... 1. 1. 1.]
Distancia: 86.394444 
[1. 1. 1. ... 1. 1. 1.]
Distancia: 0.000000 


In [78]:
a.update("Homer.png")
a.update("Homer.png")
a.update("Homer.png")
a.update("Homer.png")
a.update("Homer.png")


10000
Norm 32809.163964 
10000
Norm 42207.241274 
10000
Norm 51830.890326 
10000
Norm 61574.435994 
10000
Norm 71388.802651 


In [ ]:
a.forget("Lisa.png")

In [ ]:
a.forget("Bart2.png")

In [57]:
x1=np.array([1,1,1])

In [64]:
NN=hopfield(x2)

3
[[ 1 -1 -1]
 [-1  1  1]
 [-1  1  1]]
Norm 3.000000 


In [65]:
NN.W_p()

Wp:
[[ 1 -1 -1]
 [-1  1  1]
 [-1  1  1]]
w:
[ 3.00000000e+00  6.16297582e-33 -7.50963641e-17]
v:
[[ 5.77350269e-01  6.51147040e-17 -6.09781659e-01]
 [-5.77350269e-01 -7.07106781e-01 -7.75129861e-01]
 [-5.77350269e-01  7.07106781e-01  1.65348202e-01]]


In [67]:
NN.W_p()

Wp:
[[0. 0. 0.]
 [0. 0. 2.]
 [0. 2. 0.]]
w:
[ 2. -2.  0.]
v:
[[ 0.          0.          1.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.70710678 -0.70710678  0.        ]]


In [ ]:
NN.size()

In [63]:
x2=np.array([-1,1,1])

In [66]:
NN.update(x1)

W3:
[[2 0 0]
 [0 2 2]
 [0 2 2]]
WL:
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Wp:
[[0. 0. 0.]
 [0. 0. 2.]
 [0. 2. 0.]]
Norm 2.828427 


In [45]:
input= np.array([1,1,1 ,-1])

In [68]:
NN.query(x1)

[0. 2. 2.]
[-1.  1.  1.]
Distancia: 1.732051 
[-1.  1.  1.]
[-1.  1.  1.]
Distancia: 0.000000 
[-1.  1.  1.]


In [ ]:
input= np.array([1,1,-1 ,-1])

In [ ]:
NN.query(input)

In [29]:
NN.W_p()

Wp:
[[ 1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1 -1  1  1  1  1]
 [-1 -1 -1 -1  1 -1 -1 -1 -1]
 [ 1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1 -1  1  1  1  1]]
w:
[ 0.00000000e+00  9.00000000e+00 -5.55111512e-17  3.03269024e-31
 -1.40960244e-32  1.89510559e-33  4.85113887e-50 -7.11883232e-67
  3.04569343e-65]
v:
[[-0.94280904  0.33333333  0.11785113  0.09878024 -0.71433595 -0.92389979
  -0.92613664  0.94280904  0.94280904]
 [ 0.11785113  0.33333333  0.11785113 -0.01234753  0.08929199  0.11548747
   0.11576708 -0.11785113 -0.11785113]
 [ 0.11785113  0.33333333  0.11785113  0.07645537  0.39988447  0.20164263
   0.11576708 -0.11785113 -0.11785113]
 [ 0.11785113  0.33333333  0.11785113  0.27241748 -0.42557341  0.25720435
   0.11576708 -0.11785113 -0.11785113]
 [-0.11785113 -0.33333333 -0.11785113 -0.12176119 -0.18308055 -0.06037679
   0.0463782   0.11785113  0.11785113]
 [ 0.1

In [ ]:
input= np.array([1,1,1 ,-1])

In [34]:
NN.forget(x1)

9
x2:
[ 1  1  1  1 -1  1  1  1  1]
Wp:
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Norm 0.000000 


In [20]:
NN=hopfield(x2)

9
[[ 1 -1 -1 -1  1 -1  1 -1 -1]
 [-1  1  1  1 -1  1 -1  1  1]
 [-1  1  1  1 -1  1 -1  1  1]
 [-1  1  1  1 -1  1 -1  1  1]
 [ 1 -1 -1 -1  1 -1  1 -1 -1]
 [-1  1  1  1 -1  1 -1  1  1]
 [ 1 -1 -1 -1  1 -1  1 -1 -1]
 [-1  1  1  1 -1  1 -1  1  1]
 [-1  1  1  1 -1  1 -1  1  1]]
Norm 9.000000 


In [35]:
NN.W_p()

Wp:
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
w:
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
v:
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [36]:
NN.update(x2)

W3:
[[ 1. -1. -1. -1.  1. -1.  1. -1. -1.]
 [-1.  1.  1.  1. -1.  1. -1.  1.  1.]
 [-1.  1.  1.  1. -1.  1. -1.  1.  1.]
 [-1.  1.  1.  1. -1.  1. -1.  1.  1.]
 [ 1. -1. -1. -1.  1. -1.  1. -1. -1.]
 [-1.  1.  1.  1. -1.  1. -1.  1.  1.]
 [ 1. -1. -1. -1.  1. -1.  1. -1. -1.]
 [-1.  1.  1.  1. -1.  1. -1.  1.  1.]
 [-1.  1.  1.  1. -1.  1. -1.  1.  1.]]
WL:
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Wp:
[[ 0. -1. -1. -1.  1. -1.  1. -1. -1.]
 [-1.  0.  1.  1. -1.  1. -1.  1.  1.]
 [-1.  1.  0.  1. -1.  1. -1.  1.  1.]
 [-1.  1.  1.  0. -1.  1. -1.  1.  1.]
 [ 1. -1. -1. -1.  0. -1.  1. -1. -1.]
 [-1.  1.  1.  1. -1.  0. -1.  1.  1.]
 [ 1. -1. -1. -1.  1. -1.  0. -1. -1.]
 [-1.  1.  1.  1. -1.  1. -1.  0.  1.]
 [-1.  1.  1.  1. -1.  1. -1.  1.  0.]]
Norm 8.485281

In [37]:
NN.W_p()

Wp:
[[ 0. -1. -1. -1.  1. -1.  1. -1. -1.]
 [-1.  0.  1.  1. -1.  1. -1.  1.  1.]
 [-1.  1.  0.  1. -1.  1. -1.  1.  1.]
 [-1.  1.  1.  0. -1.  1. -1.  1.  1.]
 [ 1. -1. -1. -1.  0. -1.  1. -1. -1.]
 [-1.  1.  1.  1. -1.  0. -1.  1.  1.]
 [ 1. -1. -1. -1.  1. -1.  0. -1. -1.]
 [-1.  1.  1.  1. -1.  1. -1.  0.  1.]
 [-1.  1.  1.  1. -1.  1. -1.  1.  0.]]
w:
[-1.+0.00000000e+00j  8.+0.00000000e+00j -1.+0.00000000e+00j
 -1.+0.00000000e+00j -1.+0.00000000e+00j -1.+7.72473569e-17j
 -1.-7.72473569e-17j -1.+0.00000000e+00j -1.+0.00000000e+00j]
v:
[[-0.94280904+0.j         -0.33333333+0.j         -0.04854624+0.j
   0.00322447+0.j         -0.00803441+0.j         -0.00959084-0.01671721j
  -0.00959084+0.01671721j -0.00603266+0.j         -0.00299975+0.j        ]
 [-0.11785113+0.j          0.33333333+0.j          0.89850236+0.j
  -0.06718928+0.j          0.27969535+0.j          0.15041744+0.3249477j
   0.15041744-0.3249477j   0.13975548+0.j         -0.01434868+0.j        ]
 [-0.11785113+0.j        

In [24]:
NN.update(x1)

W3:
[[ 1. -1. -1. -1.  1. -1.  3. -1. -1.]
 [-1.  1.  3.  3. -3.  3. -1.  3.  3.]
 [-1.  3.  1.  3. -3.  3. -1.  3.  3.]
 [-1.  3.  3.  1. -3.  3. -1.  3.  3.]
 [ 1. -3. -3. -3.  1. -3.  1. -3. -3.]
 [-1.  3.  3.  3. -3.  1. -1.  3.  3.]
 [ 3. -1. -1. -1.  1. -1.  1. -1. -1.]
 [-1.  3.  3.  3. -3.  3. -1.  1.  3.]
 [-1.  3.  3.  3. -3.  3. -1.  3.  1.]]
WL:
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Wp:
[[ 0. -1. -1. -1.  1. -1.  3. -1. -1.]
 [-1.  0.  3.  3. -3.  3. -1.  3.  3.]
 [-1.  3.  0.  3. -3.  3. -1.  3.  3.]
 [-1.  3.  3.  0. -3.  3. -1.  3.  3.]
 [ 1. -3. -3. -3.  0. -3.  1. -3. -3.]
 [-1.  3.  3.  3. -3.  0. -1.  3.  3.]
 [ 3. -1. -1. -1.  1. -1.  0. -1. -1.]
 [-1.  3.  3.  3. -3.  3. -1.  0.  3.]
 [-1.  3.  3.  3. -3.  3. -1.  3.  0.]]
Norm 20.59126

In [39]:
NN.W_p()

Wp:
[[ 0. -1. -1. -1.  1. -1.  1. -1. -1.]
 [-1.  0.  1.  1. -1.  1. -1.  1.  1.]
 [-1.  1.  0.  1. -1.  1. -1.  1.  1.]
 [-1.  1.  1.  0. -1.  1. -1.  1.  1.]
 [ 1. -1. -1. -1.  0. -1.  1. -1. -1.]
 [-1.  1.  1.  1. -1.  0. -1.  1.  1.]
 [ 1. -1. -1. -1.  1. -1.  0. -1. -1.]
 [-1.  1.  1.  1. -1.  1. -1.  0.  1.]
 [-1.  1.  1.  1. -1.  1. -1.  1.  0.]]
w:
[-1.+0.00000000e+00j  8.+0.00000000e+00j -1.+0.00000000e+00j
 -1.+0.00000000e+00j -1.+0.00000000e+00j -1.+7.72473569e-17j
 -1.-7.72473569e-17j -1.+0.00000000e+00j -1.+0.00000000e+00j]
v:
[[-0.94280904+0.j         -0.33333333+0.j         -0.04854624+0.j
   0.00322447+0.j         -0.00803441+0.j         -0.00959084-0.01671721j
  -0.00959084+0.01671721j -0.00603266+0.j         -0.00299975+0.j        ]
 [-0.11785113+0.j          0.33333333+0.j          0.89850236+0.j
  -0.06718928+0.j          0.27969535+0.j          0.15041744+0.3249477j
   0.15041744-0.3249477j   0.13975548+0.j         -0.01434868+0.j        ]
 [-0.11785113+0.j        