In [52]:
import numpy as np
import numpy as np
import copy
from PIL import Image
from numpy import linalg as LA

In [158]:
def softmax(x):
    orig_shape = x.shape

    # Matrix
    if len(x.shape) > 1:
        softmax = np.zeros(orig_shape)
        for i,col in enumerate(x):
            #print(i,col)
            softmax[i] = np.exp(col - np.max(col))/np.sum(np.exp(col - np.max(col)))
        # Vector
        else:
            softmax = np.exp(x - np.max(x))/np.sum(np.exp(x - np.max(x)))
    return softmax

In [159]:
#def softmax_vectorize(x):
#    return np.exp(x - np.max(x))/np.sum(np.exp(x - np.max(x)))

In [160]:
X = np.array([[1, 1, 10, 12, 5, 0, 17],[-1,11, 0, 4, 5, 10, 7], [3, 13, -10, 4, 15, 0,6]])
print(X)

[[  1   1  10  12   5   0  17]
 [ -1  11   0   4   5  10   7]
 [  3  13 -10   4  15   0   6]]


In [161]:
beta=28
ep=[1, 1, 0,  5, 5,8 , 70]

In [162]:
a=np.dot(X,ep)
print(a)

[1277  625  531]


In [163]:
a = np.expand_dims(a, axis=0)
print(a)

[[1277  625  531]]


In [164]:
#a=np.array([[91,91,91]])

In [165]:
softmax(a)

array([[1.00000000e+000, 6.91827465e-284, 0.00000000e+000]])

In [166]:
np.dot(np.transpose(X),np.transpose(softmax(a)) )

array([[1.00000000e+000],
       [1.00000000e+000],
       [1.00000000e+001],
       [1.20000000e+001],
       [5.00000000e+000],
       [6.91827465e-283],
       [1.70000000e+001]])

In [167]:
np.dot(np.transpose(X),np.transpose(softmax(a)) )


array([[1.00000000e+000],
       [1.00000000e+000],
       [1.00000000e+001],
       [1.20000000e+001],
       [5.00000000e+000],
       [6.91827465e-283],
       [1.70000000e+001]])

In [175]:
def loop_(beta,X,epsilon):
    #print(X)
    #for i in range(2*len(epsilon)):
    for i in range(2):
        a=np.dot(X,epsilon)
        #print("#### a #####")
        #print(a)
        #print("#### b #####")
        b = np.expand_dims(a, axis=0)
        #print(b)
        #print("#### epsilon #####")
        softmax(b)
        epsilon = np.dot(np.transpose(X),np.transpose(softmax(b)))
        epsilon = np.squeeze(epsilon)
        print(epsilon)
    return epsilon
    
    
    
    

In [64]:
loop_(beta,X,ep)

[1.00000000e+000 1.00000000e+000 1.00000000e+001 1.20000000e+001
 5.00000000e+000 6.91827465e-283 1.70000000e+001]
[1.00000000e+000 1.00000000e+000 1.00000000e+001 1.20000000e+001
 5.00000000e+000 3.33100649e-155 1.70000000e+001]
[1.00000000e+000 1.00000000e+000 1.00000000e+001 1.20000000e+001
 5.00000000e+000 3.33100649e-155 1.70000000e+001]
[1.00000000e+000 1.00000000e+000 1.00000000e+001 1.20000000e+001
 5.00000000e+000 3.33100649e-155 1.70000000e+001]
[1.00000000e+000 1.00000000e+000 1.00000000e+001 1.20000000e+001
 5.00000000e+000 3.33100649e-155 1.70000000e+001]
[1.00000000e+000 1.00000000e+000 1.00000000e+001 1.20000000e+001
 5.00000000e+000 3.33100649e-155 1.70000000e+001]
[1.00000000e+000 1.00000000e+000 1.00000000e+001 1.20000000e+001
 5.00000000e+000 3.33100649e-155 1.70000000e+001]
[1.00000000e+000 1.00000000e+000 1.00000000e+001 1.20000000e+001
 5.00000000e+000 3.33100649e-155 1.70000000e+001]
[1.00000000e+000 1.00000000e+000 1.00000000e+001 1.20000000e+001
 5.00000000e+00

array([1.00000000e+000, 1.00000000e+000, 1.00000000e+001, 1.20000000e+001,
       5.00000000e+000, 3.33100649e-155, 1.70000000e+001])

In [65]:
################### loading test vectors ###################

In [66]:
vec1=np.load("/media/german/51f3aae9-4042-4d37-b815-440a1b6b695d/data2/Homer5.npy") 

In [67]:
vec2=np.load("/media/german/51f3aae9-4042-4d37-b815-440a1b6b695d/data2/Lisa23.npy") 

In [68]:
vec3=np.load("/media/german/51f3aae9-4042-4d37-b815-440a1b6b695d/data2/Bart1.npy") 

In [69]:
X=np.vstack((vec1,vec2,vec3))

In [70]:
X=np.array[[vec1,vec2,vec3]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [71]:
vec4=np.load("/media/german/51f3aae9-4042-4d37-b815-440a1b6b695d/data2/Lisa11.npy")

In [72]:
ep=vec4

In [73]:
ep = np.squeeze(ep)

In [74]:
print(ep)

[-0.08983571  0.02090269 -0.06639389 -0.02221609 -0.06316955 -0.37134844
 -0.10894614 -0.05211455 -0.08936886 -0.12769572 -0.02626571 -0.13161325
  0.08485465 -0.19168147 -0.10084593 -0.11935412  0.08299053 -0.13002425
 -0.11112196 -0.10368099 -0.11902498 -0.04883286 -0.09845122  0.01469846
 -0.08411475 -0.046952   -0.12778911 -0.09329707 -0.05192159 -0.19736664
 -0.04448415 -0.12602608 -0.08373059 -0.11177926 -0.03293488 -0.03350252
 -0.10866132 -0.07150804 -0.05335077 -0.09108429 -0.44276288 -0.11897115
 -0.1046713  -0.32838994 -0.11681022 -0.04294022 -0.13529684 -0.11462264
 -0.09417023 -0.09406014  0.09969313 -0.09084909 -0.02668031  0.01177444
 -0.03129882 -0.12168586 -0.107627   -0.09990346 -0.08617347 -0.10413997
 -0.0759757  -0.07739692 -0.11977763 -0.08994261]


In [75]:
Xo=loop_(beta,X,ep)

[-0.08341824  0.04272124 -0.0800169   0.16086446 -0.0884415  -0.10316423
 -0.11532447 -0.05363778 -0.10461015 -0.11784328  0.113453   -0.12300633
  0.07606953 -0.157581   -0.10094938 -0.1304399  -0.11901959 -0.14389853
 -0.11742128 -0.10735515 -0.13232547 -0.07510372 -0.11960232  0.08642221
 -0.08068953 -0.01950362 -0.13661009 -0.10723716 -0.05933829 -0.16299774
 -0.03506773 -0.10988786 -0.09086316 -0.10075296 -0.00066706 -0.05491076
 -0.10187326 -0.05598288 -0.04219073 -0.0937066  -0.39156806 -0.10394087
 -0.09582298 -0.19116488 -0.1077248  -0.03721779 -0.12976076 -0.12207627
 -0.10785907 -0.06156842  0.07795113 -0.08374006  0.05405832 -0.04759746
  0.02379776 -0.11776337 -0.11108138 -0.08791456 -0.0846819  -0.08456553
  0.02966649 -0.0947062  -0.11303453 -0.09249175]
[-0.08341616  0.03808051 -0.07930363  0.16380996 -0.08811163 -0.09492768
 -0.11534084 -0.05402045 -0.10352483 -0.11699139  0.11188163 -0.12273843
  0.07704549 -0.16035122 -0.09965757 -0.12938333 -0.11927786 -0.14355047
 

In [76]:
 Xo= np.expand_dims(Xo, axis=0)

In [77]:
np.save("/media/german/51f3aae9-4042-4d37-b815-440a1b6b695d/data2/Xo.npy", Xo)

In [78]:
print(Xo)

[[-0.08343867  0.03755538 -0.07921674  0.16394953 -0.08808459 -0.09358014
  -0.11535001 -0.05407738 -0.10337869 -0.11689007  0.11174679 -0.12272498
   0.07703981 -0.16073166 -0.09950949 -0.12924232 -0.11924129 -0.14350477
  -0.11681035 -0.10728196 -0.13201049 -0.0746036  -0.11893366  0.09188037
  -0.07983363 -0.02515757 -0.13550343 -0.10713916 -0.05958872 -0.15911752
  -0.03486422 -0.11026708 -0.0900601  -0.10003619  0.00636216 -0.06173007
  -0.10167986 -0.05564445 -0.04181676 -0.09347486 -0.3938651  -0.10320177
  -0.09517369 -0.19067098 -0.10677377 -0.03696534 -0.13001311 -0.12184117
  -0.10734583 -0.06158268  0.07408473 -0.0834086   0.04969675 -0.0453663
   0.02764439 -0.11686907 -0.10998223 -0.08704403 -0.08792424 -0.08413964
   0.02767698 -0.09415096 -0.11257496 -0.09164806]]


In [79]:
np.savetxt("/media/german/51f3aae9-4042-4d37-b815-440a1b6b695d/data2/Xo.csv", Xo, delimiter=",")

In [ ]:
####################### Modern Hopfield Network ################################3

In [340]:
import numpy as np
import copy
from PIL import Image
from numpy import linalg as LA

In [341]:
%matplotlib inline 

In [342]:
def convert_to_flat(image):
        img = Image.open(image).convert('L')
        newsize = (100, 100)
        img = img.resize(newsize)  
        arr = np.array(img)
        shape = arr.shape
        flat_arr = np.ndarray.flatten(arr).astype(float)
        vector = np.matrix(flat_arr)
        vector2 = copy.deepcopy(flat_arr)
        vector2.astype(np.float32)
        arr2 = np.asarray(vector2).reshape(shape)
        img2 = Image.fromarray(arr, 'L')
        img2.show()
        return flat_arr

In [343]:
def convert_to_image(image):
    shape=(100,100)
    arr2 = np.asarray(image).reshape(shape)
    img2 = Image.fromarray(arr2)
    img2.show()
    return 

In [350]:
vec1=convert_to_flat("/media/german/51f3aae9-4042-4d37-b815-440a1b6b695d/data2/Homer8B.jpg")
vec2=convert_to_flat("/media/german/51f3aae9-4042-4d37-b815-440a1b6b695d/data2/Lisa14.jpg")
vec3=convert_to_flat("/media/german/51f3aae9-4042-4d37-b815-440a1b6b695d/data2/Bart1B.jpg")
vec4=convert_to_flat("/media/german/51f3aae9-4042-4d37-b815-440a1b6b695d/data2/Homer8C.jpg")
ep=convert_to_flat("/media/german/51f3aae9-4042-4d37-b815-440a1b6b695d/data2/Lisa14A1.jpg")

In [351]:
X=np.vstack((vec1,vec2,vec3,vec4))

In [352]:
beta=20

In [353]:
Xo=loop_(beta,X,ep)

[255. 255. 255. ... 234. 225. 233.]
[255. 255. 255. ... 234. 225. 233.]


In [354]:
convert_to_image(Xo)


(eog:14410): GLib-GObject-CRITICAL **: 19:12:33.655: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(eog:14410): EOG-WARNING **: 19:12:33.655: Error al obtener la información del archivo «/tmp/tmp7xdee7li.PNG»: No existe el archivo o el directorio

(eog:14410): GLib-GObject-CRITICAL **: 19:12:33.671: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(eog:14410): EOG-WARNING **: 19:12:33.671: Error al obtener la información del archivo «/tmp/tmppj2zdk1m.PNG»: No existe el archivo o el directorio

(eog:14410): GLib-GObject-CRITICAL **: 19:12:33.676: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(eog:14410): EOG-WARNING **: 19:12:33.676: Error al obtener la información del archivo «/tmp/tmppj2zdk1m.PNG»: No existe el archivo o el directorio
