In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.preprocessing import normalize
import numpy as np
from numpy import linalg as LA

In [2]:
# initialize list of lists
data = [[10,120,30,'Bart'],  [ 14,123,45,"Lisa"],[ 11,123,33,"Bart"],[ 14,123,45,"Lisa"],]
# Create the pandas DataFrame
df = pd.DataFrame(data, columns = [ 'Age','Height',"Weight",'Name'])
print(df)

   Age  Height  Weight  Name
0   10     120      30  Bart
1   14     123      45  Lisa
2   11     123      33  Bart
3   14     123      45  Lisa


In [3]:

features = [ 'Age','Height',"Weight"]
# Separating out the features
x = df.loc[:, features].values
# Separating out the target
y = df.loc[:,['Name']].values
# Standardizing the features
x = StandardScaler().fit_transform(x)

In [4]:
print(x)

[[-1.26025208 -1.73205081 -1.20740686]
 [ 0.98019606  0.57735027  0.98787834]
 [-0.70014004  0.57735027 -0.76834982]
 [ 0.98019606  0.57735027  0.98787834]]


In [5]:

pca = PCA(n_components=3)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2','principal component 3'])

In [6]:

#pca = PCA(n_components=1)
#principalComponents = pca.fit_transform(x)
#principalDf = pd.DataFrame(data = principalComponents
#             , columns = ['principal component 1'])

In [7]:
finalDf = pd.concat([principalDf, df[['Name']]], axis = 1)
principalComponents

array([[ 2.39597258e+00, -5.52613803e-01,  4.50175239e-17],
       [-1.48688149e+00, -2.43320155e-01,  8.10401546e-17],
       [ 5.77790399e-01,  1.03925411e+00,  4.50175239e-17],
       [-1.48688149e+00, -2.43320155e-01,  8.99489323e-18]])

In [8]:
print(finalDf)

   principal component 1  principal component 2  principal component 3  Name
0               2.395973              -0.552614           4.501752e-17  Bart
1              -1.486881              -0.243320           8.104015e-17  Lisa
2               0.577790               1.039254           4.501752e-17  Bart
3              -1.486881              -0.243320           8.994893e-18  Lisa


In [9]:
#pca.explained_variance_ratio_
#print(pca.singular_values_)
print(pca.components_)

[[-0.60392893 -0.52717012 -0.59779722]
 [-0.33793054  0.84863181 -0.40697297]
 [ 0.72185372 -0.04376881 -0.69066019]]


In [10]:
pca.explained_variance_ratio_

array([8.74679956e-01, 1.25320044e-01, 8.91797474e-34])

In [11]:
###############  Ojas ####################

In [12]:
nb_samples =4
df=df.loc[:, df.columns.drop('Name')]
samples=df.to_numpy()
print(samples)

[[ 10 120  30]
 [ 14 123  45]
 [ 11 123  33]
 [ 14 123  45]]


In [13]:
norm1 = StandardScaler().fit_transform(samples)
print (norm1)

[[-1.26025208 -1.73205081 -1.20740686]
 [ 0.98019606  0.57735027  0.98787834]
 [-0.70014004  0.57735027 -0.76834982]
 [ 0.98019606  0.57735027  0.98787834]]


In [14]:
weights = [-0.34878339,-0.9874051, 0.87048954]
#weights =2.0 * (np.random.random((1,3)) - 0.5)
#weights=weights.tolist()
print(weights)


[-0.34878339, -0.9874051, 0.87048954]


In [15]:
def update_data():
    global weights, presented_example, weights_history, lrate_history,norm1
    index_sample = np.random.randint(0,nb_samples)
    output = np.dot(np.transpose(norm1[index_sample]) , weights) 
    weights = weights + update_data.lrate * ( np.transpose(norm1[index_sample])*output - np.transpose(weights)*output*output)
    update_data.epoch = update_data.epoch + 1
    update_data.lrate = update_data.initial_lrate / (float(update_data.epoch)/nb_samples+1.0)
    return weights

In [16]:
update_data.epoch = 1
initial_lrate = 0.1
update_data.maxepoch = 1 * nb_samples # 10 presentations of all the samples
update_data.initial_lrate = initial_lrate
update_data.lrate = update_data.initial_lrate

In [17]:
w=weights
new_x=norm1
print("#########norm1 ##############")
print(norm1)

def iteraciones(k):
    global norm1,w,weights,weights0,new_x
    for i in range(k):
        #while LA.norm(weights)<0.99999: 
        for j in range(100000):
            weights=update_data()
        weights=update_data()    
        weights=weights/LA.norm(weights) #Avoid overflow
        w.append(weights.tolist())
        out = np.dot(norm1 , weights)
        print("######## out #########")
        print(out)
        print("######## weigths #########")
        print(weights)
        y = np.outer(out,weights)
        print("######### y ##############")
        print(y)
        print("######### norm1 ##############")
        print(norm1)
        if i==0:
            print("######### 0 ##############")
            norm1=norm1-y
            norm2=norm1.copy()
        if i==1:
            print("######### 1 ##############")
            norm1=norm1-norm2-y
            norm3=norm1.copy()
        if i==3:
            print("######### 2 ##############")
            norm1=norm1-norm2-norm3-y
            
            
        print("######### norm1.. ##############")
        print(norm1)     
        update_data.epoch = 1
        initial_lrate = 0.4
        update_data.maxepoch = 1 * nb_samples # 10 presentations of all the samples
        update_data.initial_lrate = initial_lrate
        update_data.lrate = update_data.initial_lrate
        weights = [-0.34878339,-0.9874051, 0.87048954] #Fix for randon weights
    #print(w)   
iteraciones(4)
w.pop(0)
w.pop(0)
w.pop(0)
print(w)

#########norm1 ##############
[[-1.26025208 -1.73205081 -1.20740686]
 [ 0.98019606  0.57735027  0.98787834]
 [-0.70014004  0.57735027 -0.76834982]
 [ 0.98019606  0.57735027  0.98787834]]
######## out #########
[ 2.39544831 -1.48711117  0.57877403 -1.48711117]
######## weigths #########
[-0.60434055 -0.52636087 -0.59809425]
######### y ##############
[[-1.44766655 -1.26087026 -1.43270385]
 [ 0.89872158  0.78275714  0.88943264]
 [-0.34977662 -0.30464401 -0.34616142]
 [ 0.89872158  0.78275714  0.88943264]]
######### norm1 ##############
[[-1.26025208 -1.73205081 -1.20740686]
 [ 0.98019606  0.57735027  0.98787834]
 [-0.70014004  0.57735027 -0.76834982]
 [ 0.98019606  0.57735027  0.98787834]]
######### 0 ##############
######### norm1.. ##############
[[ 0.18741448 -0.47118054  0.22529699]
 [ 0.08147447 -0.20540687  0.0984457 ]
 [-0.35036342  0.88199428 -0.4221884 ]
 [ 0.08147447 -0.20540687  0.0984457 ]]
######## out #########
[ 0.55488099  0.24191239 -1.03870577  0.24191239]
######## weig

In [691]:
print(w)

[[-0.6042254257110072, -0.5269719146924157, -0.5976723484065174], [0.3356296847650361, -0.8489738569647718, 0.4081618611468762], [-0.2561457825058316, -0.7250892466719311, 0.6392455885379317]]


In [692]:
np.dot(w[0],w[1])

0.0006423316884973678

In [693]:
np.dot(w[1],w[2])

0.7905273553019969

In [454]:
LA.norm(w[2]) 

1.0